Implement `Bento.Decoder.transform/2`
folz/bento pull request #24
Opened 2023-02-08 21:26 UTC by mogeko

Replace the old `Posison.Decode.decode/2` with `Bento.Decoder.transform/2`.

As you can see, the benchmark shows that there is no obvious difference in performance.

Earlier times:

```txt
## ParserBench
benchmark name      iterations   average time 
single (Bencodex)       500000   4.02 µs/op
single (Bento)          500000   6.36 µs/op
single (bencode)        100000   16.51 µs/op
multi (Bencodex)          5000   666.52 µs/op
multi (Bento)             1000   1110.96 µs/op
single (bencoder)         1000   1276.72 µs/op
multi (bencode)           1000   1941.72 µs/op
multi (bencoder)           500   7130.18 µs/op
```

Nowadays:

```txt
## ParserBench
benchmark name      iterations   average time 
single (Bencodex)       500000   4.24 µs/op
single (Bento)          500000   6.36 µs/op
single (bencode)        100000   14.28 µs/op
multi (Bencodex)          2000   603.69 µs/op
multi (Bento)             1000   1148.87 µs/op
single (bencoder)         1000   1511.96 µs/op
multi (bencode)           1000   1732.82 µs/op
multi (bencoder)           500   6760.21 µs/op
```

At this stage, I need to write some additional unit tests and documents to check if I have missed anything.

Moreover, I encapsulated `Bento.Parser` by the way.

2023-02-08 22:45 UTC, folz commented
Caught up from your comment https://github.com/folz/bento/pull/15#issuecomment-1416881549 - this also sounds good to me. LMK when you're ready if you'd like a review!

2023-02-08 23:08 UTC, mogeko reviewed
Yes, I think I'm ready. :sunglasses: @folz

2023-02-09 10:01 UTC, folz requested changes
Nice work, and agreed that making our own implementation of the `as` concept was worth it.

The implementation looks overall solid. I have two blocking requests, but once those are addressed I think this should be good to merge.

2023-02-09 10:01 UTC, folz commented on lib/bento/decoder.ex
> +  @type opts :: [as: map() | list() | struct()]
Checking - is there a test covering when `as` is a list? I saw the UserList case, but I think that is also a struct which holds a list, not a top-level list.

Alternatively, if it's not supported to pass a list to `as` and this is intended to handle structs containing lists, would it be possible to have `list()` be in an internal type but not exposed through this public API type?

2023-02-09 10:01 UTC, folz commented on lib/bento/decoder.ex
> +  defguardp is_transable(v) when is_map(v) or is_list(v)
nit: For future readability, could you change this so the word isn't abbreviated? `is_transformable(v)`

2023-02-09 12:46 UTC, mogeko commented on lib/bento/decoder.ex
> +  @type opts :: [as: map() | list() | struct()]
Thanks for your feedback!

Yes, whether it is a top-level `list()` or a `list()` in the Struct, we can transform it in the same way.

I reconstructed the logic of handling `list()` to completely distinguish it from the code that handles the `map()`.

At the same time, I added additional unit test cases for the **top-level list** and **top-level map**.

2023-02-17 10:55 UTC, merged